#Dataset Collection

In [92]:
# Loading dataset in variable df

df = pd.read_csv('/content/patient_data.csv')
df.head()

,C,Age,History,Patient,TakeMedication,Severity,BreathShortness,VisualChanges,NoseBleeding,Whendiagnoused,Systolic,Diastolic,ControlledDiet,Stages
0,Male,18-34,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
1,Female,18-34,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
2,Male,35-50,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
3,Female,35-50,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
4,Male,51-64,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)

#Data Preparation

In [91]:
# Loading important libraries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [93]:
df.isnull().sum()

C                  0
Age                0
History            0
Patient            0
TakeMedication     0
Severity           0
BreathShortness    0
VisualChanges      0
NoseBleeding       0
Whendiagnoused     0
Systolic           0
Diastolic          0
ControlledDiet     0
Stages             0
dtype: int64

In [94]:
df.rename(columns={'C':'Gender'}, inplace=True)
df

,Gender,Age,History,Patient,TakeMedication,Severity,BreathShortness,VisualChanges,NoseBleeding,Whendiagnoused,Systolic,Diastolic,ControlledDiet,Stages
0,Male,18-34,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
1,Female,18-34,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
2,Male,35-50,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
3,Female,35-50,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
4,Male,51-64,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1820,Female,35-50,Yes,No,No,Sever,No,No,No,>5 Years,111 - 120,70 - 80,No,NORMAL
1821,Male,51-64,Yes,No,No,Sever,No,No,No,>5 Years,111 - 120,70 - 80,No,NORMAL
1822,Female,51-64,Yes,No,No,Sever,No,No,No,>5 Years,111 - 120,70 - 80,No,NORMAL
1823,Male,65+,Yes,No,No,Sever,No,No,No,>5 Years,111 - 120,70 - 80,No,NORMAL
1824,Female,65+,Yes,No,No,Sever,No,No,No,>5 Years,111 - 120,70 - 80,No,NORMAL

In [95]:
df['TakeMedication'].replace({'Yes ':'Yes'}, inplace=True)
df['NoseBleeding'].replace({'No ':'No'}, inplace=True)
df['Systolic'].replace({'100+':'100 - 110'}, inplace=True)
df['Systolic'].replace({'121- 130':'121 - 130'}, inplace=True)
df['Stages'].replace({'HYPERTENSION (Stage-2).':'HYPERTENSION (Stage-2)'}, inplace=True)
df['Stages'].replace({'HYPERTENSIVE CRISI':'HYPERTENSION CRISIS'}, inplace=True)

print((df['Diastolic']=='130+').sum())
print((df['Diastolic']=='100+').sum())

4
237

/tmp/ipykernel_335/136801949.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['TakeMedication'].replace({'Yes ':'Yes'}, inplace=True)
/tmp/ipykernel_335/136801949.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['NoseBleeding'].replace({'No ':'No'}, inplace=True)
/tmp/ipykernel_335/136801949.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Systolic'].replace({'100+':'100 - 110'}, inplace=True)
/tmp/ipykernel_335/136801949.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Stages'].replace({'HYPERTENSION (Stage-2).':'HYPERTENSION (Stage-2)'}, inplace=True)

In [96]:
df['Diastolic'].replace({'130+':'100+'}, inplace=True)

/tmp/ipykernel_335/1944431796.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Diastolic'].replace({'130+':'100+'}, inplace=True)

In [97]:
print(df.duplicated().sum())

477

In [98]:
df.drop_duplicates(inplace=True)

#Categorical Data Encoding

In [99]:
nominal_features = ['Gender', 'History', 'Patient', 'TakeMedication',
                    'BreathShortness', 'VisualChanges', 'NoseBleeding', 'ControlledDiet']

ordinal_features = [f for f in df.columns if f not in nominal_features]
ordinal_features.remove('Stages')

print(nominal_features)
print(ordinal_features)

['Gender', 'History', 'Patient', 'TakeMedication', 'BreathShortness', 'VisualChanges', 'NoseBleeding', 'ControlledDiet']
['Age', 'Severity', 'Whendiagnoused', 'Systolic', 'Diastolic']

In [100]:
for col in nominal_features:
    if set(df[col].unique()) == set(['Yes', 'No']):
        df[col] = df[col].map({'No': 0, 'Yes': 1})
    elif col == 'Gender':
        df[col] = df[col].map({'Male': 0, 'Female': 1})


df['Age'] = df['Age'].map({'18-34': 1, '35-50': 2, '51-64': 3, '65+': 4})

df['Severity'] = df['Severity'].replace({'Mild': 0, 'Moderate': 1, 'Severe': 2, 'Sever': 2})

df['Whendiagnoused'] = df['Whendiagnoused'].map({
    '<1 Year': 1,
    '1-5 Years': 2,
    '>5 Years': 3
})

df['Stages'] = df['Stages'].map({
    'NORMAL': 0,
    'HYPERTENSION (Stage-1)': 1,
    'HYPERTENSION (Stage-2)': 2,
    'HYPERTENSIVE CRISIS': 3
})

df['Systolic'] = df['Systolic'].map({
    '100 - 110': 0,
    '111 - 120': 1,
    '121 - 130': 2,
    '130+': 3})

df['Diastolic'] = df['Diastolic'].map({
    '70 - 80': 0,
    '81 - 90': 1,
    '91 - 100': 2,
    '100+': 3
})

/tmp/ipykernel_335/15746749.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Severity'] = df['Severity'].replace({'Mild': 0, 'Moderate': 1, 'Severe': 2, 'Sever': 2})

In [101]:
df['Severity'].unique()

array([0, 2, 1])

In [102]:
print(df['Systolic'].unique())

[1 2 3 0]

In [103]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[ordinal_features] = scaler.fit_transform(df[ordinal_features])

In [104]:
df

,Gender,Age,History,Patient,TakeMedication,Severity,BreathShortness,VisualChanges,NoseBleeding,Whendiagnoused,Systolic,Diastolic,ControlledDiet,Stages
0,0,0.000000,1,0,0,0.0,0,0,0,0.0,0.333333,0.333333,0,1.0
1,1,0.000000,1,0,0,0.0,0,0,0,0.0,0.333333,0.333333,0,1.0
2,0,0.333333,1,0,0,0.0,0,0,0,0.0,0.333333,0.333333,0,1.0
3,1,0.333333,1,0,0,0.0,0,0,0,0.0,0.333333,0.333333,0,1.0
4,0,0.666667,1,0,0,0.0,0,0,0,0.0,0.333333,0.333333,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1596,1,0.333333,1,0,0,1.0,0,0,0,1.0,0.333333,0.000000,0,0.0
1597,0,0.666667,1,0,0,1.0,0,0,0,1.0,0.333333,0.000000,0,0.0
1598,1,0.666667,1,0,0,1.0,0,0,0,1.0,0.333333,0.000000,0,0.0
1599,0,1.000000,1,0,0,1.0,0,0,0,1.0,0.333333,0.000000,0,0.0
1600,1,1.000000,1,0,0,1.0,0,0,0,1.0,0.333333,0.000000,0,0.0